name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey, Thanks for Showing Interest in the issue, wait for a mantainer to assign it to you"
        pr-message: "Thanks for your Contribution!!.Wait for a Maintainer to approve the changes, if no one responds in 12 hours try requesting review from the maintainers"
